name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./app
        
      - name: Run linter
        run: ./gradlew checkstyleMain
        working-directory: ./app
        
      - name: Run test
        run: ./gradlew test
        working-directory: ./app
        
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: build/reports/jacoco/test/jacocoTestReport.xml:jacoco
