name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./app/gradlew
        
      - name: Run linter
        run: ./app/gradlew checkstyleMain
        
      - name: Run test
        run: ./app/gradlew test
        
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: ./app/gradlew jacocoTestReport
          coverageLocations: app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
