name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Run linter
        working-directory: ./app
        run: ./gradlew checkstyleMain
      - name: Run test
        working-directory: ./app
        run: ./gradlew test

  coverage:
    name: "Test Coverage"
    runs-on: "ubuntu-latest"
    if: ${{ github.event_name == 'push' }} # Publish coverage only for push commits, not PRs.
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: run tests and instrument coverage
      run: make report

    - name: publish code coverage to code-climate (duh)
      uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        debug: true
        coverageLocations: |
          ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
